name: Build and test React App

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest=
    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: yarn --cwd ./App/ticker            #install dependencies, point to package.json
    - run: yarn --cwd ./App/ticker test       #Run unit test
    - run: yarn --cwd ./App/ticker run build --if-present #Build
      env:
        CI: true
